### ISSUE TITLE
Massive update

### ISSUE THREAD

**Issue by fils** [fils/nabu#16]
@valentinedwv this is a massive revision of the code.

I removed much, updated much.   Really sorry to push this much out in one fell swoop..  I'll try not to do this again but felt it was needed.   I tried to keep some notes (below).   If you feel up to to taking a look at it, great.   

# Change Log

* Removed several options that were experiments by me like
txtai, tika, etc and all the related pkg, pkg/cli and internal
files associated with them.  Basically, removing experiments which 
I will bring back but as proper branches for testing and review
and not mixed into dev or master directly.  
* Removed several functions that were no longer being used.
Basically, anything not referenced was removed.
* Some functions were exported that didn't need to be, ie they
were only internal to a given package.  They were unexported which
in go is simply making them start lower case and refactoring.
* One or two files had several functions in them.  I split these into 
individual files so, for the most part, any exported function is in 
its own file.  It might have a few unexported support functions in it
as well.
* Documentation updates including some d2 diagrams to better describe
the flow of events
* Updated root.go to deal with the --prefix flag correctly.  So the
var passed is a proper []string now.  
* Reduced some log chatter.  Lots of unneeded logs lines 
removed and some trapped behind error catches or moved from Info
to Trace.
* Created several testing and inspection SPARQL functions in docs/sparql
* URN pattern resolved. This was done in several place (because I am
really a terrible programmer) so I made a single function for this 
at internal/graph/mintURN.go   This is now an ADR entry. 
* Added decisions directory for ADRs with URN pattern as first one
at decisions/0001-URN-decision.md
* Renamed jena to the more generic bulk
* Added an endpointBulk to the config file since this is needed for bulk 
loading vs the SPARQL update calls. 
* Centralize JSON-LD proc and options into ldproc.go
* TESTING:  Meili service reads server address from environment variable

TODO
* add an input for the location of the schema file, pipelined into ldproc.go already
* Align meili pipeJS2Array with object/pipecopy.go so that there is common
code use.   just use pipecopy then mod the JSON to address meili format?
* Make a framing pipeline for marqo  "pipeframe"

Working status and supporting documentation for the following

[x] prefix loading works with blaze (sparql update)
[x] prune loading works with blaze (sparql update)

[x] prefix loading works with jena (sparql update)
[x] prune works with jena (sparql update)

[X] prefix loading works with graphdb (sparql update)
[ ] prune loading works with graphdb (sparql update)

[x] bulk loading works with jena
[x] bulk loading works with graphdb

**Comment by fils** [comment]
@valentinedwv 
Dave, I made some changes and pushed them to my branch.  Does that then update the pull request as well?    I am trying to see if when I do a new commit and push to the branch that is part of a pending pull request if it updates things so that you can review them again.

I think that is how it works, but let me know if it doesn't or if there is something else I should do.

**Comment by valentinedwv** [comment]
Yes, see the changes in the PR
