### ISSUE TITLE
A cli entry for stats/report separate from prune / snip

### ISSUE THREAD

**Issue by fils** [fils/nabu#18]
I wonder if prune could not be two things:

collect|validate|stats, then pass object to prune/Snip
Then add a cli for stats/report, to just dump a file info from collect|validate|stat, with options for a brief summary or a detailed report with all the URN information.

We could do the same thing in gleaner for the sitemaps, etc.

**Comment by valentinedwv** [comment]
We can/do this in earthcube utilities.
