### ISSUE TITLE
Add graphs prefix to hold bulk versions of the repo graphs

### ISSUE THREAD

**Issue by fils** [fils/nabu#28]
Mod the bulk workflow in nabu to:

* output the bulk files into a prefix graphs/latest
* also have a graphs/archive to move the old version to
* do we need the output to be quads and or triples

can be a mod of services/bulkloader

**Comment by valentinedwv** [comment]
Need to have an option for quads. Digging.

api.ToRDF calls [api.GenerateNodeMap with default graph name](https://github.com/piprate/json-gold/blob/6ddbe6e6f19fff2bc6deb02fa6f628b0ce5f1fa1/ld/api_to_rdf.go#L23)

So, maybe skip ToRdf, and directly call [GenerateNodeMap()](https://github.com/piprate/json-gold/blob/6ddbe6e6f19fff2bc6deb02fa6f628b0ce5f1fa1/ld/api_generate_node_map.go#L24)

Probably write our Own version of ToRDF with a graphName feature added.
