### ISSUE TITLE
Release graph is triples not quads

### ISSUE THREAD

**Issue by fils** [fils/nabu#31]
The release graph is generating triples, not quads.   I really want quads as a sort of "nabu prov" statement.  However, since the triples is there now, make this an option.  However, I think I want the quads the default and the triples the option.

**Comment by valentinedwv** [comment]
#28 #25

**Comment by MBcode** [comment]
25 is the new name of [126](https://github.com/gleanerio/gleaner/issues/126) that I have been talking about, and now [planning](https://github.com/earthcube/earthcube_utilities/blob/dcm/earthcube_utilities/docs/get_crawled_quads.md) around this fix, for this week
