### ISSUE TITLE
releases http://schema.org in some files

### ISSUE THREAD

**Issue by valentinedwv** [fils/nabu#48]
Think there may be an issue with summon... 
but for consistency, we should probably map to http://schema.org or https://schema.org

The geocodes_demo_datasets run produces http://schema.org

**Comment by valentinedwv** [comment]
While summon can write out the files. it still might be a good option to allow for fixes at prep for graph time.

**Comment by fils** [comment]
@valentinedwv  I am going to see about this in the nabu workflow too..   I'll look at options and we can discuss them.
